#!/bin/sh

LAP="eDP1"
AUX="DP1"
xrandr --output $LAP --auto --primary --output $AUX --off

~/.config/bspwm/minimal_panel.py | lemonbar -p -g x20 -F "#FFF"&
#compton --daemon --backend glx --vsync none --unredir-if-possible  --paint-on-overlay \
#--glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method buffer-age
~/.fehbg &

bspc config border_width                  2
bspc config window_gap                   20

bspc config top_padding                  15 
bspc config bottom_padding               15
bspc config left_padding                 15
bspc config right_padding                15

bspc config -m $LAP top_padding          30

bspc config normal_border_color          "#0a3749"
bspc config active_border_color          "#d26937"
bspc config focused_border_color         "#33859e"
bspc config presel_feedback_color        "#0a3749"

bspc config split_ratio                  0.50
bspc config borderless_monocle           true
bspc config gapless_monocle              true
#bspc config focus_by_distance           true
#bspc config history_aware_focus         true
bspc config honor_size_hints             false
bspc config click_to_focus               true
bspc config remove_unplugged_monitors    true

# ~/scripts/monitor_setup.sh expects the desktops in a certain state
bspc monitor $LAP -d I II III IV V VI VII VIII IX X

bspc rule -a URxvt:quake-term \
    monitor=focused desktop=focused state=floating \
    border=off sticky=on focus=on center=on
bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Gvim center=on

#~/scripts/enable_monitor.sh
