#!/bin/sh

LAP="eDP1"
AUX="DP1"
xrandr --output $LAP --auto --primary --output $AUX --off

#~/.config/bspwm/minimal_panel.py | lemonbar -p -g x20 -F "#FFF"&
~/.fehbg &
$HOME/.config/polybar/launch.sh &

# enables compositing (kills battery)
#compton --daemon \
#        --backend glx \
#        --vsync none \
#        --unredir-if-possible \
#        --paint-on-overlay \
#        --fade-delta=10 \
#        --fade-in-step=0.1 \
#        --fade-out-step=0.1 \
#        --glx-no-stencil --glx-no-rebind-pixmap --glx-swap-method buffer-age

bspc config border_width                3
bspc config window_gap                  35

#bspc config top_padding                 5
#bspc config bottom_padding              5
#bspc config left_padding                5
#bspc config right_padding               5

#bspc config -m $LAP top_padding         30

bspc config normal_border_color         "#282828"
bspc config focused_border_color        "#504945"
bspc config presel_feedback_color       "#282828"

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
#bspc config focus_by_distance           true
#bspc config history_aware_focus         true
bspc config honor_size_hints            false
bspc config click_to_focus              true
bspc config remove_unplugged_monitors   true

# ~/scripts/monitor_setup.sh expects the desktops in a certain state
bspc monitor $LAP -d I II III IV V VI VII VIII IX X

bspc rule -a URxvt:quake-term \
    monitor=focused desktop=focused state=floating \
    border=off sticky=on focus=on center=on
bspc rule -a Zathura state=tiled
bspc rule -a emacs state=tiled
#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Gvim center=on
