#! /bin/sh

~/.config/bspwm/panel_status | lemonbar -g x20 &
compton --backend glx --vsync opengl-swc --paint-on-overlay --glx-no-stencil -b &

bspc config border_width         2
bspc config window_gap          10

bspc config top_padding         30
bspc config bottom_padding      10
bspc config left_padding        10
bspc config right_padding       10

bspc config normal_border_color   "#0a3749"
bspc config active_border_color   "#d26937"
bspc config focused_border_color  "#33859e"
bspc config presel_feedback_color "#0a3749"

bspc config split_ratio               0.50
bspc config borderless_monocle        true
bspc config gapless_monocle           true
bspc config focus_by_distance         true
bspc config history_aware_focus       true
bspc config honor_size_hints          true
bspc config click_to_focus            true
bspc config remove_unplugged_monitors true

# monitor_setup.sh expects the desktops in a certain state
bspc monitor ^1 -d I II III IV V VI VII VIII IX X
bspc monitor ^2 -d dummy

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Gvim state=pseudo_tiled

sleep 0.05
~/scripts/monitor_setup.sh
