#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ]; then
	echo "Panel is already running." >&2
	exit 1
fi

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &

