#!/bin/bash

clock()
{
	TIME=$(date "+%a %b %d")
	echo -n $TIME
}

day()
{
	DAY=$(date "+%R")
	echo -n $DAY
}

volume()
{
	#MUTE=$(amixer sget -M Master PCH
	VOLUME=$(amixer sget -M Master PCH | egrep -o "[0-9]+%")
	echo -n "$VOLUME%"
}

battery()
{
	BATPERC=$(cat /sys/class/power_supply/BAT0/capacity)
	echo -n "$BATPERC%%"
}

#desktop()
#{
	# bspc subscribe report
	# see:
	# man bspc: report format
#}

# replace this loop with some event-based system to save battery
# see inotify api to detect changes in battery level
# volume change events can be triggered directly by the volume key
while true; do
	echo "%{r}bat: $(battery) | vol: $(volume) | $(day)  $(clock)"
	sleep 5
done
