#!/bin/bash
# note: there's a bug when booting with a monitor connected, handle this by
# connecting the monitor after bspwm has started.
#
# useful information
# querying monitors:
#     $ bspc query -D -m $MONITOR --names
#
# letting bspwm find monitor names:
#     LAP=$(bspc query -M -m ^1) # name of the laptop/primary monitor (eDP1)
#     AUX=$(bspc query -M -m ^2)  # name of the second monitor (DP1)
#
# new desktops are added to the end of existing desktops
#
# originally I had this script add a dummy desktop to the end of the desktops
# on the aux monitor, so that when switching to single monitor mode bspwm
# wouldn't throw a fit. Turns out we don't need this extra desktop anymore.

LAP="eDP1"
AUX="DP1"

if (xrandr | egrep "^$AUX connected"); then
	xrandr --output $LAP --auto --primary \
	       --output $AUX --auto --right-of $LAP
	# send desktops 6 - 10 to the connected monitor
	for i in {6..10}; do
		# we use ^6 because the desktops get shifted back to fill
		# the "hole" left behind by removing the desktop from the monitor
		bspc desktop ^6 --to-monitor $AUX
	done

	bspc monitor $AUX -o VI VII VIII IX X

    # new monitor has no panel
    #bspc config -m $AUX top_padding 10

    echo "$LAP: $(bspc query -D -m $LAP --names | tr '\n' ' ')"
    echo "$AUX: $(bspc query -D -m $AUX --names | tr '\n' ' ')"

    sleep 0.01
    ~/.fehbg

else
	echo "external monitor not found"
    exit 1
fi

